// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-trips.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_trips_default = defineTool({
  name: "list_trips",
  title: "List trips",
  description: "List the signed-in user's travel projects (id, name, dates).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("travel_projects").select("id,name,start_date,end_date,visibility").order("start_date", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { trips: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-trip-itinerary.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_trip_itinerary_default = defineTool2({
  name: "get_trip_itinerary",
  title: "Get trip itinerary",
  description: "Get the itinerary items for one of the signed-in user's trips, ordered by day and time.",
  inputSchema: {
    trip_id: z.string().uuid().describe("The travel project id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trip_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: project, error: projErr } = await supabase.from("travel_projects").select("id,name,start_date,end_date").eq("id", trip_id).maybeSingle();
    if (projErr) return { content: [{ type: "text", text: projErr.message }], isError: true };
    if (!project) return { content: [{ type: "text", text: "Trip not found" }], isError: true };
    const { data: items, error } = await supabase.from("itinerary_items").select("id,day_number,start_time,end_time,description,google_maps_url,price,persons,icon_type,sort_order").eq("project_id", trip_id).order("day_number", { ascending: true }).order("start_time", { ascending: true, nullsFirst: false }).order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { trip: project, items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "prnbldqlgslmqagnhpvu";
var mcp_default = defineMcp({
  name: "peitravel-mcp",
  title: "PeiTravel MCP",
  version: "0.1.0",
  instructions: "Tools for the signed-in PeiTravel user. Use `list_trips` to enumerate their travel projects, and `get_trip_itinerary` to read the day-by-day items of one trip.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_trips_default, get_trip_itinerary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
